<?php
//file : app/constants.php

//activity type
define('ACTIVITY_SHARE',  1);
define('ACTIVITY_REGISTER',  2);
define('ACTIVITY_COMMENT',  3);
define('ACTIVITY_POST',  4);
define('ACTIVITY_PHOTO',  5);
define('ACTIVITY_INFOGRAFIS',  6);
define('ACTIVITY_POLL',  7);
define('ACTIVITY_INVITE_MEMBER',  8);
define('ACTIVITY_REFERENCE_POLLING',  9);
define('ACTIVITY_REFERRED_POLLING',  9);
define('ACTIVITY_PREMIUM',  10);
define('ACTIVITY_WINNER',  11);
define('ACTIVITY_REGISTER_FROM_INVITATION',  12);
define('ACTIVITY_PHOTO_APPROVED',  13);
define('ACTIVITY_PHOTO_SUBMITED',  14);
define('ACTIVITY_GRAPHIC_APPROVED',  15);
define('ACTIVITY_GRAPHIC_SUBMITED',  16);
define('ACTIVITY_POST_APPROVED',  17);
define('ACTIVITY_POST_SUBMITED',  18);
define('ACTIVITY_PREMIUM_COMMENT',  19);
define('ACTIVITY_OTHER',  20);
define('ACTIVITY_REPLY_COMMENT', 21);
define('ACTIVITY_LIKE_COMMENT', 22);
define('ACTIVITY_APPROVE_EVENT_PARTICIPANT', 23);
define('ACTIVITY_REJECT_EVENT_PARTICIPANT', 39);
define('ACTIVITY_PENDING_EVENT_PARTICIPANT', 40);
define('ACTIVITY_APPROVE_EVENT_PARTICIPANT_TEAM', 24);
define('ACTIVITY_REJECT_EVENT_PARTICIPANT_TEAM', 41);
define('ACTIVITY_PENDING_EVENT_PARTICIPANT_TEAM', 42);
define('ACTIVITY_INVITE_MEMBER_TO_JOIN_TEAM', 38);
define('ACTIVITY_ZETCON_VOTING', 25);
define('ACTIVITY_ARTICLE_APPROVED', 26);
define('ACTIVITY_ARTICLE_SUBMITED', 27);
define('ACTIVITY_ARTICLE_REJECTED', 33);
define('ACTIVITY_ARTICLE_SPAMMED', 34);
define('ACTIVITY_NEW_BADGE', 28);
define('ACTIVITY_SUBMIT_WEEKLY_CHALLENGE', 29);
define('ACTIVITY_SUBMIT_NATIONAL_CHALLENGE', 32);
define('ACTIVITY_REDEEM_POINT', 30);
define('ACTIVITY_REDEMPTION_APPROVED', 44);
define('ACTIVITY_REDEMPTION_REJECTED', 45);
define('ACTIVITY_PHOTO_REJECTED',  35);
define('ACTIVITY_GRAPHIC_REJECTED',  36);
define('ACTIVITY_POST_REJECTED',  37);

// ROLE
define('ROLE_MEMBER', 1);
define('ROLE_ADMIN', 4);
define('ROLE_EDITOR', 6);
define('ROLE_CONTRIBUTOR', 9);
define('ROLE_FINANCE', 10);
define('ROLE_OPERATIONAL', 11);
define('ROLE_MANAGER', 12);
define('ROLE_COACH', 13);
define('ROLE_INVESTOR', 14);
define('ROLE_RENTER', 15);
define('ROLE_INVESTOR_FINANCE', 16);
define('ROLE_SUPER_ADMIN', 99);
define('ROLE_HEAD_COACH', 17);
define('ROLE_FREELANCE_COACH', 18);

//conversation notification
define('CONVERSATION_NOTIFICATION_LIMIT', 6);

//notification notification
define('NOTIFICATION_LIMIT', 6);

//cache
define('DB_QUERY_CACHE_PERIOD_FAST', 1);  //in minutes
define('DB_QUERY_CACHE_PERIOD_MEDIUM', 15);  //in minutes
define('DB_QUERY_CACHE_PERIOD_SLOW', 60);  //in minutes

define('STORE_ORDER_STATUS_INITIAL', 1);
define('STORE_ORDER_STATUS_WAITING_PAYMENT', 2);
define('STORE_ORDER_STATUS_WAITING_CONFIRMATION', 3);
define('STORE_ORDER_STATUS_PACKING', 4);
define('STORE_ORDER_STATUS_SENT', 5);
define('STORE_ORDER_STATUS_DELIVERED', 6);
define('STORE_ORDER_STATUS_COMPLETED', 7);
define('STORE_ORDER_STATUS_CANCELLED', 8);
define('STORE_ORDER_STATUS_RETURN', 9);
define('STORE_ORDER_STATUS_REFUND', 10);
define('STORE_ORDER_STATUS_EXPIRED', 11);